import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#B65356',
  primaryLight: '#CE6265',
  accent: '#E9999C',
  accentBg: 'rgba(233,153,156,0.3)',
  accentBgLight: 'rgba(233,153,156,0.22)',
  background: '#FFF9F9',
  white: '#FFFFFF',
  border: '#D9D9D9',
  textPrimary: '#000000',
  textSecondary: '#888888',
  textMuted: '#555555',
  success: '#059669',
  successBg: '#D1FAE5',
  warning: '#F59E0B',
  warningBg: '#FEF3C7',
  gray: '#E5E7EB',
};

export const shared = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: 10,
    marginTop: 10,
    padding: 12,
  },
  cardTitle: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  sep: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 9,
  },
  btnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: 10,
    padding: 11,
    marginHorizontal: 10,
    marginBottom: 8,
  },
  btnPrimaryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  btnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 10,
    padding: 11,
    marginHorizontal: 10,
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: colors.primaryLight,
    backgroundColor: 'transparent',
  },
  btnSecondaryText: {
    color: colors.primaryLight,
    fontSize: 12,
    fontWeight: '600',
  },
  btnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 10,
    padding: 11,
    marginHorizontal: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'transparent',
  },
  btnOutlineText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  topBarTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.accentBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icoWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.accentBg,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 4,
  },
  infoLabel: {
    fontSize: 9,
    color: colors.textSecondary,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: 12,
    color: colors.textPrimary,
    marginTop: 2,
  },
  versionText: {
    textAlign: 'center',
    fontSize: 9,
    color: colors.textSecondary,
    marginVertical: 14,
  },
});
